# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BLEDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('ble_device_id', models.CharField(max_length=256)),
                ('registered_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
    ]
