# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bledevice',
            name='id',
        ),
        migrations.AlterField(
            model_name='bledevice',
            name='ble_device_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
